import { lazy, type Component } from 'solid-js';

// Lazy-load all demos for code splitting
const demos: Record<string, Component> = {
  'button': lazy(() => import('./button-demo')),
  'card': lazy(() => import('./card-demo')),
  'input': lazy(() => import('./input-demo')),
  'textarea': lazy(() => import('./textarea-demo')),
  'badge': lazy(() => import('./badge-demo')),
  'alert': lazy(() => import('./alert-demo')),
  'separator': lazy(() => import('./separator-demo')),
  'label': lazy(() => import('./label-demo')),
  'skeleton': lazy(() => import('./skeleton-demo')),
  'spinner': lazy(() => import('./spinner-demo')),
  'table': lazy(() => import('./table-demo')),
  'kbd': lazy(() => import('./kbd-demo')),
  'accordion': lazy(() => import('./accordion-demo')),
  'checkbox': lazy(() => import('./checkbox-demo')),
  'switch': lazy(() => import('./switch-demo')),
  'slider': lazy(() => import('./slider-demo')),
  'progress': lazy(() => import('./progress-demo')),
  'tabs': lazy(() => import('./tabs-demo')),
  'toggle': lazy(() => import('./toggle-demo')),
  'toggle-group': lazy(() => import('./toggle-group-demo')),
  'avatar': lazy(() => import('./avatar-demo')),
  'breadcrumb': lazy(() => import('./breadcrumb-demo')),
  'pagination': lazy(() => import('./pagination-demo')),
  'tooltip': lazy(() => import('./tooltip-demo')),
  'select': lazy(() => import('./select-demo')),
  'dialog': lazy(() => import('./dialog-demo')),
  'alert-dialog': lazy(() => import('./alert-dialog-demo')),
  'popover': lazy(() => import('./popover-demo')),
  'dropdown-menu': lazy(() => import('./dropdown-menu-demo')),
  'sheet': lazy(() => import('./sheet-demo')),
  'aspect-ratio': lazy(() => import('./aspect-ratio-demo')),
  'collapsible': lazy(() => import('./collapsible-demo')),
  'scroll-area': lazy(() => import('./scroll-area-demo')),
  'resizable': lazy(() => import('./resizable-demo')),
  'empty': lazy(() => import('./empty-demo')),
  'calendar': lazy(() => import('./calendar-demo')),
  'carousel': lazy(() => import('./carousel-demo')),
  'form': lazy(() => import('./form-demo')),
  'radio-group': lazy(() => import('./radio-group-demo')),
  'native-select': lazy(() => import('./native-select-demo')),
  'input-otp': lazy(() => import('./input-otp-demo')),
  'combobox': lazy(() => import('./combobox-demo')),
  'hover-card': lazy(() => import('./hover-card-demo')),
  'context-menu': lazy(() => import('./context-menu-demo')),
  'menubar': lazy(() => import('./menubar-demo')),
  'navigation-menu': lazy(() => import('./navigation-menu-demo')),
  'command': lazy(() => import('./command-demo')),
  'sidebar': lazy(() => import('./sidebar-demo')),
  'drawer': lazy(() => import('./drawer-demo')),
  'sonner': lazy(() => import('./sonner-demo')),
  'chart': lazy(() => import('./chart-demo')),
  'input-group': lazy(() => import('./input-group-demo')),
  'button-group': lazy(() => import('./button-group-demo')),
  'field': lazy(() => import('./field-demo')),
  'item': lazy(() => import('./item-demo')),
};

export function getDemo(slug: string): Component | undefined {
  return demos[slug];
}
