import { defineConfig } from 'vitest/config';
import path from 'path';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

function alias(name: string, dir: 'core' | 'solid') {
  return { [`@radix-solid/${name}`]: path.resolve(__dirname, `packages/${dir}/${name}/src`) };
}

function shadcnAlias(name: string) {
  return { [`@shadcn-solid/${name}`]: path.resolve(__dirname, `packages/shadcn/${name}/src`) };
}

export default defineConfig({
  // Use esbuild's built-in JSX transform with solid-js/h hyperscript runtime.
  // vite-plugin-solid causes "Unknown file extension .ts" errors with vitest,
  // so we use the h-mode JSX runtime which is compatible with esbuild's automatic JSX transform.
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'solid-js/h',
  },
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['packages/**/src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      include: ['packages/**/src/**/*.{ts,tsx}'],
      exclude: ['**/*.test.*', '**/index.ts'],
    },
  },
  resolve: {
    alias: {
      // Core packages
      ...alias('primitive', 'core'),
      ...alias('number', 'core'),
      ...alias('rect', 'core'),
      // Solid utility packages
      ...alias('compose-refs', 'solid'),
      ...alias('context', 'solid'),
      ...alias('direction', 'solid'),
      ...alias('focus-guards', 'solid'),
      ...alias('use-previous', 'solid'),
      ...alias('use-escape-keydown', 'solid'),
      ...alias('use-size', 'solid'),
      ...alias('use-rect', 'solid'),
      ...alias('use-controllable-state', 'solid'),
      // Solid foundation packages
      ...alias('slot', 'solid'),
      '@radix-solid/primitive-component': path.resolve(__dirname, 'packages/solid/primitive-component/src'),
      ...alias('presence', 'solid'),
      ...alias('visually-hidden', 'solid'),
      ...alias('arrow', 'solid'),
      ...alias('portal', 'solid'),
      ...alias('collection', 'solid'),
      ...alias('focus-scope', 'solid'),
      ...alias('dismissable-layer', 'solid'),
      ...alias('roving-focus', 'solid'),
      ...alias('popper', 'solid'),
      ...alias('announce', 'solid'),
      // Phase 4: id utility + simple/medium UI components
      ...alias('id', 'solid'),
      ...alias('label', 'solid'),
      ...alias('separator', 'solid'),
      ...alias('aspect-ratio', 'solid'),
      ...alias('accessible-icon', 'solid'),
      ...alias('progress', 'solid'),
      ...alias('toggle', 'solid'),
      ...alias('avatar', 'solid'),
      ...alias('switch', 'solid'),
      ...alias('checkbox', 'solid'),
      ...alias('collapsible', 'solid'),
      // Phase 5: medium complexity components
      ...alias('toggle-group', 'solid'),
      ...alias('radio-group', 'solid'),
      ...alias('accordion', 'solid'),
      ...alias('tabs', 'solid'),
      ...alias('toolbar', 'solid'),
      ...alias('scroll-area', 'solid'),
      ...alias('slider', 'solid'),
      ...alias('tooltip', 'solid'),
      // Phase 6: complex components
      ...alias('dialog', 'solid'),
      ...alias('alert-dialog', 'solid'),
      ...alias('popover', 'solid'),
      ...alias('hover-card', 'solid'),
      ...alias('toast', 'solid'),
      ...alias('navigation-menu', 'solid'),
      ...alias('form', 'solid'),
      ...alias('menu', 'solid'),
      ...alias('dropdown-menu', 'solid'),
      ...alias('context-menu', 'solid'),
      ...alias('menubar', 'solid'),
      ...alias('select', 'solid'),
      ...alias('use-effect-event', 'solid'),
      ...alias('one-time-password-field', 'solid'),
      ...alias('password-toggle-field', 'solid'),
      // Phase 8: shadcn components
      ...shadcnAlias('utils'),
      ...shadcnAlias('button'),
      ...shadcnAlias('card'),
      ...shadcnAlias('input'),
      ...shadcnAlias('textarea'),
      ...shadcnAlias('badge'),
      ...shadcnAlias('breadcrumb'),
      ...shadcnAlias('alert'),
      ...shadcnAlias('skeleton'),
      ...shadcnAlias('spinner'),
      ...shadcnAlias('table'),
      ...shadcnAlias('kbd'),
      ...shadcnAlias('pagination'),
      ...shadcnAlias('label'),
      ...shadcnAlias('separator'),
      ...shadcnAlias('dialog'),
      ...shadcnAlias('alert-dialog'),
      ...shadcnAlias('accordion'),
      ...shadcnAlias('checkbox'),
      ...shadcnAlias('collapsible'),
      ...shadcnAlias('context-menu'),
      ...shadcnAlias('dropdown-menu'),
      ...shadcnAlias('hover-card'),
      ...shadcnAlias('menubar'),
      ...shadcnAlias('navigation-menu'),
      ...shadcnAlias('popover'),
      ...shadcnAlias('progress'),
      ...shadcnAlias('radio-group'),
      ...shadcnAlias('scroll-area'),
      ...shadcnAlias('select'),
      ...shadcnAlias('slider'),
      ...shadcnAlias('switch'),
      ...shadcnAlias('tabs'),
      ...shadcnAlias('toggle'),
      ...shadcnAlias('toggle-group'),
      ...shadcnAlias('tooltip'),
      ...shadcnAlias('sheet'),
      ...shadcnAlias('form'),
      ...shadcnAlias('field'),
      ...shadcnAlias('input-group'),
      ...shadcnAlias('button-group'),
      ...shadcnAlias('native-select'),
      ...shadcnAlias('empty'),
      ...shadcnAlias('item'),
      ...shadcnAlias('aspect-ratio'),
      ...shadcnAlias('avatar'),
      ...shadcnAlias('input-otp'),
      ...shadcnAlias('combobox'),
      ...shadcnAlias('drawer'),
      ...shadcnAlias('sidebar'),
      ...shadcnAlias('sonner'),
      ...shadcnAlias('command'),
      ...shadcnAlias('calendar'),
      ...shadcnAlias('carousel'),
      ...shadcnAlias('chart'),
      ...shadcnAlias('resizable'),
    },
    conditions: ['development', 'browser'],
  },
});
